# Generated by Django 6.0.2 on 2026-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
