# Generated by Django 5.0.4 on 2026-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='habits', to='skills.skill'),
        ),
    ]
