# Generated by Django 6.0.2 on 2026-02-21 21:08

import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                validators=[habits.validators.validate_habit_frequency]
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[habits.validators.validate_habit_name_length],
            ),
        ),
    ]
