# Generated by Django 5.0.4 on 2026-03-09 16:03

import django.db.models.deletion
import skills.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[skills.validators.validate_skill_title_length])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/')),
                ('category', models.CharField(choices=[('mental', 'Mental'), ('physical', 'Physical'), ('creative', 'Creative'), ('technical', 'Technical'), ('social', 'Social')], default='mental', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
            ],
        ),
    ]
