# Generated by Django 6.0.2 on 2026-02-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="category",
            new_name="categories",
        ),
    ]
