# Generated by Django 6.0.2 on 2026-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_rename_category_skill_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="skills/"),
        ),
    ]
