# Generated by Django 6.0.2 on 2026-02-21 21:08

import skills.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_skill_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[skills.validators.validate_skill_title_length],
            ),
        ),
    ]
